### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by lafin** [lafin/puller#1]
- [ ] web ui
- [ ] auto update by schedule
- [ ] update by hook
- [ ] flags (all, running)
- [ ] notify about fail
- [ ] rollback after fail
- [ ] puller's network
